package wdk;

/**
 *These are properties that are to be loaded from properties.xml. They will
 * provide custom labels and other UI details for our Wolfieball Draft Kit
 * application. The reason for doing this is to swap out UI text and icons
 * easily without having to touch our code. It also allows for language 
 * independence.
 * 
 * @author Brandon
 */
public enum WDK_PropertyType {
    // LOADED FROM properties.xml
    PROP_APP_TITLE,
    
    // APPLICATION ICONS
    NEW_DRAFT_ICON,
    LOAD_DRAFT_ICON,
    SAVE_DRAFT_ICON,
    VIEW_DRAFT_ICON,
    EXPORT_PAGE_ICON,
    DELETE_ICON,
    EXIT_ICON,
    ADD_ICON,
    MINUS_ICON,
    MOVE_UP_ICON,
    MOVE_DOWN_ICON,
    FANTASY_TEAMS_ICON,
    PLAYERS_ICON,
    FANTASY_STANDINGS_ICON,
    DRAFT_SUMMARY_ICON,
    MLB_TEAMS_ICON,
    EDIT_ICON,
    PLAY_ICON,
    PAUSE_ICON,
    STAR_ICON,
    
    
    //APPLICATION TOOLTIPS FOR BUTTONS
    NEW_DRAFT_TOOLTIP,
    LOAD_DRAFT_TOOLTIP,
    SAVE_DRAFT_TOOLTIP,
    VIEW_DRAFT_TOOLTIP,
    EXPORT_PAGE_TOOLTIP,
    DELETE_TOOLTIP,
    EXIT_TOOLTIP,
    ADD_ITEM_TOOLTIP,
    REMOVE_ITEM_TOOLTIP,
    MOVE_UP_TOOLTIP,
    MOVE_DOWN_TOOLTIP,
    ADD_TOOLTIP,
    REMOVE_TOOLTIP,
    FANTASY_TEAMS_TOOLTIP,
    PLAYERS_TOOLTIP,
    FANTASY_STANDINGS_TOOLTIP,
    DRAFT_SUMMARY_TOOLTIP,
    MLB_TEAMS_TOOLTIP,
    SEARCH_TOOLTIP,
    ADD_TEAM_TOOLTIP,
    REMOVE_TEAM_TOOLTIP,
    EDIT_TEAM_TOOLTIP,
    AUTO_TOOLTIP,
    PLAY_TOOLTIP,
    PAUSE_TOOLTIP,
    
    // FOR DRAFT EDIT WORKSPACE
    DRAFT_HEADING_LABEL,
    FANTASY_TEAMS_LABEL,
    PLAYERS_LABEL,
    FANTASY_STANDINGS_LABEL,
    DRAFT_SUMMARY_LABEL,
    MLB_TEAMS_LABEL,
    SEARCH_LABEL,
    ALL_LABEL,
    C_LABEL,
    FIRST_LABEL,
    CI_LABEL,
    THIRD_LABEL,
    SECOND_LABEL,
    MI_LABEL,
    SS_LABEL,
    OF_LABEL,
    U_LABEL,
    P_LABEL,
    FIRST_NAME_LABEL,
    LAST_NAME_LABEL,
    TEAM_LABEL,
    QP_LABEL,
    YEAR_OF_BIRTH_LABEL,
    R_LABEL,
    W_LABEL,
    HR_LABEL,
    SW_LABEL,
    RBI_LABEL,
    K_LABEL,
    SB_LABEL,
    ERA_LABEL,
    BA_LABEL,
    WHIP_LABEL,
    EV_LABEL,
    NOTES_LABEL,
    SELECT_FANTASY_TEAM_LABEL,
    DRAFT_NAME_LABEL,
    STARTING_LINEUP_LABEL,
    TAXI_SQUAD_LABEL,
    POSITION_LABEL,
    PRO_TEAM_LABEL,
    PICK_LABEL,
    FANTASY_TEAM_LABEL,
    TEAM_NAME_LABEL,
    PLAYERS_NEEDED_LABEL,
    MONEY_LEFT_LABEL,
    PP_LABEL,
    TOTAL_POINTS_LABEL,
    
    // FOR PLAYER EDITING
    CONTRACT_LABEL,
    SALARY_LABEL,
    
    // ERROR DIALOG MESSAGES
    
    
    // VERIFICATION MESSAGES
    NEW_DRAFT_CREATED_MESSAGE,
    DRAFT_LOADED_MESSAGE,
    DRAFT_SAVED_MESSAGE,
    SITE_EXPORTED_MESSAGE,
    SAVE_UNSAVED_WORK_MESSAGE,
    REMOVE_TEAM_MESSAGE,
    REMOVE_PLAYER_MESSAGE
    
}
